# -*- coding: utf-8 -*-
"""Traffic Sign Detection and recognition model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15b6e7a_6ezGVaSGk1uUdI4uvwmL7p_Js
"""

!pip install ultralytics roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="NbbkRMsNQxoHqz6BFwN0")
project = rf.workspace("gtsrbanno").project("traffic-sign-detection-gtsrb")
version = project.version(15)
dataset = version.download("yolov8")

from ultralytics import YOLO
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Using device:", device)

from ultralytics import YOLO

model = YOLO("yolov8m.pt")  # Medium variant for better accuracy

# ====================================================
# 🏋️ Train YOLOv8m on GTSDB Dataset (Fine-Tuned)
# ====================================================

results = model.train(
    data=f"{dataset.location}/data.yaml",  # path to your dataset config
    epochs=100,                            # longer training for better convergence
    imgsz=640,
    batch=16,
    lr0=0.0005,                            # lower learning rate for smoother updates
    optimizer="Adam",
    mosaic=0.5,                            # reduced for validation stability
    mixup=0.1,                             # reduced to preserve label clarity
    cache=True,
    pretrained=True,
    name="traffic_sign_yolov8m_finetuned",# new run name
    exist_ok=True,
    patience=10                            # early stopping if val loss plateaus
)

print("\n✅ Training completed!")
print("📂 Model saved to: runs/detect/traffic_sign_yolov8m_finetuned/weights/best.pt")

"""testing"""

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import pandas as pd
import os

# Ensure inline plotting in Colab
# %matplotlib inline

# Path to YOLOv8 results
results_dir = "runs/detect/traffic_sign_yolov8n_80ep"
csv_path = f"{results_dir}/results.csv"

if os.path.exists(csv_path):
    df = pd.read_csv(csv_path)

    # Apply rolling average for smoothing
    window = 5
    df['precision_smooth'] = df['metrics/precision(B)'].rolling(window).mean()
    df['recall_smooth'] = df['metrics/recall(B)'].rolling(window).mean()
    df['train_loss_smooth'] = df['train/box_loss'].rolling(window).mean()
    df['val_loss_smooth'] = df['val/box_loss'].rolling(window).mean()

    # Identify best epoch (lowest val loss)
    best_epoch = df['val/box_loss'].idxmin()
    best_val_loss = df['val/box_loss'][best_epoch]

    # Plotting
    plt.style.use('seaborn-v0_8-darkgrid')
    fig, axs = plt.subplots(1, 2, figsize=(14,6))

    # 📈 Validation Performance
    axs[0].plot(df['epoch'], df['precision_smooth'], label='Precision (smoothed)', color='blue')
    axs[0].plot(df['epoch'], df['recall_smooth'], label='Recall (smoothed)', color='green')
    axs[0].axvline(x=best_epoch, color='red', linestyle='--', label=f'Best Epoch: {best_epoch}')
    axs[0].set_title("Validation Performance over Epochs")
    axs[0].set_xlabel("Epoch")
    axs[0].set_ylabel("Score")
    axs[0].legend()
    axs[0].grid(True)

    # 📉 Training vs Validation Loss
    axs[1].plot(df['epoch'], df['train_loss_smooth'], label='Train Box Loss (smoothed)', color='orange')
    axs[1].plot(df['epoch'], df['val_loss_smooth'], label='Val Box Loss (smoothed)', color='purple')
    axs[1].axvline(x=best_epoch, color='red', linestyle='--', label=f'Best Epoch: {best_epoch} ({best_val_loss:.3f})')
    axs[1].set_title("Training vs Validation Box Loss")
    axs[1].set_xlabel("Epoch")
    axs[1].set_ylabel("Loss")
    axs[1].legend()
    axs[1].grid(True)

    plt.tight_layout()
    plt.savefig("learning_curves.png", dpi=300)
    plt.show()

    print("\n✅ Enhanced learning curves plotted.")
    print("📥 Saved as 'learning_curves.png' in your Colab workspace.")
else:
    print("⚠️ No training log found at:", results_dir)

# ====================================================
# 🧠 5. Test the trained YOLOv8 model on new images
# ====================================================
from google.colab import files
from IPython.display import Image, display
import os

# Upload one or more test images
print("📤 Please upload one or more traffic sign images to test:")
uploaded = files.upload()

# Run prediction for each uploaded image
for img_name in uploaded.keys():
    print(f"\n🔍 Processing image: {img_name}")

    # Run YOLOv8 prediction
    results = model.predict(source=img_name, conf=0.25, save=True, show=False)
    r = results[0]

    # Check detection results
    num_detections = len(r.boxes)
    if num_detections == 0:
        print(f"❌ No traffic signs detected in {img_name}")
    else:
        print(f"✅ {num_detections} traffic sign(s) detected in {img_name}:")
        for i, box in enumerate(r.boxes):
            cls = int(box.cls[0])      # class index
            conf = float(box.conf[0])  # confidence
            label = r.names[cls]       # class name
            print(f"   {i+1}. {label} (confidence: {conf:.2f})")

    # Construct the saved image path properly
    output_path = os.path.join(r.save_dir, img_name)
    if os.path.exists(output_path):
        display(Image(filename=output_path))
    else:
        print(f"⚠️ Could not find output image at {output_path}")

# Colab-ready: upload image(s) and optional weights, run YOLOv8, display image(s) with bounding boxes only
!pip install -q ultralytics

from ultralytics import YOLO
from google.colab import files
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.patches as patches
import numpy as np
import io, os

# Upload image(s) and optionally upload a custom weights file (.pt) named best.pt
uploaded = files.upload()
filenames = list(uploaded.keys())
img_files = [f for f in filenames if f.lower().endswith(('.jpg','.jpeg','.png'))]
weights_file = next((f for f in filenames if f.lower().endswith('.pt')), None)
if len(img_files) == 0:
    raise SystemExit("No image uploaded.")

# Choose model path: custom weights if provided else yolov8x.pt
model_path = weights_file if weights_file else "yolov8x.pt"
model = YOLO(model_path)

# Inference and display (no labels, no saved annotated images)
for img_name in img_files:
    results = model.predict(source=img_name, conf=0.05, save=False, show=False, verbose=False)
    r = results[0] if len(results) > 0 else None

    img = Image.open(img_name).convert("RGB")
    fig, ax = plt.subplots(figsize=(12,8))
    ax.imshow(img)

    boxes = np.empty((0,4))
    if r is not None and hasattr(r, "boxes"):
        try:
            boxes = r.boxes.xyxy.cpu().numpy()
        except Exception:
            try:
                boxes = np.array([b.xyxy[0].cpu().numpy() for b in r.boxes])
            except Exception:
                boxes = np.empty((0,4))

    for b in boxes:
        x1, y1, x2, y2 = map(float, b[:4])
        rect = patches.Rectangle((x1, y1), x2-x1, y2-y1, linewidth=3, edgecolor='yellow', facecolor='none')
        ax.add_patch(rect)

    ax.axis('off')
    plt.tight_layout()
    display(fig)
    plt.close(fig)

model.export(format="onnx")  # export for deployment or further use